travis:
  secure:
    BINSTAR_TOKEN: zm9JBXcencCIjUdSdgREj8z41wNjZ1TtxgbcFy3eypOAfUeYOXNqC1Hfn9kTyELklw6iafsQvjwkoTh8y6sMeYh0cnzxUUGFxA1+ctkO42F0LPn/6nSs95JBjlwD5MmAeSfO1Z0+BiIT/LAu2oTMKHUp67SXNrW4iMFtPTbnOkRmQtid8OJec9bs2DruWZ2TRpYMkCSfjWsrK86HUKa7cTpNi5TpMY3IILCqKGUuXRMeQayvmN8uVHLLzjE2iBxltVUplgTilL0ANObFQ4C70+k2Z2ar3/6YcbkmBfGSJjJ5VMMAkdFSOsgxrzaMzk5CCzKyexrBMxn6OR7psFWKK1yzfv3nAOZPPed/Z09/fHq4nvNOdmnIZMk8vQcaBEnQ3LztHJGw3DQ0FZ21sN29yOPG+Grs/v4d5+oFtKWiwgKE2vKMD8vEFpi73nk2fXdgdDvMDTe2WUj6f/Hl9iEihP/lH+Mv+A1SNnw50JFzKtXcSR/f8eEBe8yW+jV6HD469QWgnAX615TBXRDWWvYefeg6rWQLjQyRh51RokDOsXX8xYf1HvETTQMdVc7a5xxpvspL1v0IfeFiSJk+TOA3cTOLc7iHFjgdjKCYmEkVKCifGoYbbRLGkkuHRWCqzrW3LZ05JujDN6OF7Hvi2RL/AduBUZSy4a0UGPdqu+TTGwU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
