travis:
  secure:
    BINSTAR_TOKEN: Kdo5nphmosLQWJIXJtjjNOVR4R8QOgofTrbjZoUylCplhyoYyVjuQFOqFBmlMkQcCeYWJs9Bgi38mJoCqDbOflHM2/z8RBTweXM1RO9JTBHks5BN3+5n/pXcDi5aoOxeu2GYZruubEyx3E3+3sR8rgBBpwy7KFudQbIxyGkkdUJmXZHspct4t+nm6gnBC5aCRPfYtTEmsABJBVtOrKi1N6FAaF/49K15HWTReGlAw2NoW4MltoIRCdsT43QB1PBjO9IfWlhCvX32S495PeY0/EtbHn6yQtQKYz1jycDVKa6PQCVoehSR5BWtSMeUMFqKS3XkGZzpiCi/tyUzkUQLRVGx3SqrCisjXh2wghN4EthX03Y/1Mvwf4fOKC17D7ObB/smiRitd4/RfjlPuNwN7QY2HP06eDBaUMe/XC918Mw8kmWDYYvfYPtFl5EC1nBOhtYXxTq0lav/6NXgiXPR3fTD0XXC3do0hFuko7ZLSXAzXRV+g/BLSJRNLT/nLTqGwJD/n7+1Ekx4cem6ejaRZdtZfGqLnjLNmIT5u6c7eBRB+J3uq7LzpSLMRxOuG5RVWzCpsJHEW+FPeqrsc5citb1Q4qZZQTtxAn79/d9G55wrlRfQ33iJKB65nAtdn7SNTTRAAdNYriwWTCwNA6SGM0E0vvWAspIxAJMlpLbAk4s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
